[package]
name = "mcm_misc"
version = "4.0.0"
edition = "2021"
authors = ["Gooxey"]
description = "Functions, structs, and more used by applications in the MCManage Network"
readme = "README.md"
repository = "https://github.com/Gooxey/mcm_misc.git"
license-file = "LICENSE"

[dependencies]
serde_json = "1.0.87"
chrono = "0.4.22"
thiserror = "1.0"
system_shutdown = "4.0.1"
tokio = { version="1.25.0", features=["full"]}
async-recursion = "1.0.2"
async-trait = "0.1.64"

[dev-dependencies]
reqwest = { version="0.11", features=["blocking"] }