[package]
name = "mcm_misc"
version = "1.2.0"
edition = "2021"
authors = ["Gooxey"]
description = "Functions and structs used by applications in the MCManage Network"
readme = "README.md"
repository = "https://github.com/Gooxey/mcm_misc.git"
license-file = "LICENSE"

[dependencies]
serde_json = "1.0.87"
chrono = "0.4.22"