[package]
name = "mcm_proxy"
version = "1.0.0"
edition = "2021"
authors = ["Gooxey"]
description = "The core of the MCManage network."
readme = "README.md"
repository = "https://github.com/Gooxey/mcm_proxy.git"
license-file = "LICENSE"

[dependencies]
mcm_misc = { git = "https://github.com/Gooxey/mcm_misc.git", version = "1.0.0" }